from . import pos_session
from . import pos_config
from . import res_partner
from . import pos_payment_method
from . import pos_order
from . import res_config_settings
from . import res_company
from . import res_users
from . import pos_payment
