from . import fees_retention
from . import tax_unit
from . import accumulated_fees
from . import payment_concept
from . import payment_concept_line
from . import type_person
from . import signature_config
from . import economic_activity
from . import economic_branch
from . import type_withholding