from . import accumulated_fees
from . import account_move
from . import account_payment
from . import account_retention
from . import account_retention_line
from . import account_withholding_type
from . import economic_branch
from . import economic_activity
from . import fees_retention
from . import payment_concept
from . import payment_concept_line
from . import res_partner
from . import signature_config
from . import economic_activity
from . import economic_branch
from . import type_withholding
from . import account_retention_line
from . import account_retention
from . import account_move
from . import account_payment
from . import res_partner
from . import tax_unit
from . import type_person
