from . import partner_config
from . import partner_profession
from . import action_partner
from . import action_partner_previous
from . import res_partner
from . import account_move
from . import account_move_line
from . import account_payment
from . import res_users
from . import pending_debt_list
from . import member_in_debt_report