version: "3"
services:
  odoo:    
    build:
      context: Dockerfile
    container_name: ${PROJECT_NAME}
    depends_on:
      - db-odoo
    ports:
      - "${PORT_SERVICE_HOST_ODOO}:${PORT_SERVICE_CONTAINER_ODOO}"
    volumes:
      - odoo-web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./enterprise:/mnt/extra-addons
      - ./integra:/mnt/integra-addons
      #- ./custom:/mnt/custom-addons
    args:
      - ODOO_RELEASE: latest
    environment:
      - PYTHONUNBUFFERED=0
    #devices:
    #  - "/dev/ttyACM0:/dev/ttyACM0"
    restart: always
  db-odoo:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web:
  odoo-db:
