version: "3"
services:
  odoo:    
    build:
      context: .
      args:
        ODOO_RELEASE: ${ODOO_RELEASE}
    container_name: ${PROJECT_NAME}   
    networks:
      - network_odoo      
    ports:
      - "${PORT_SERVICE_HOST_ODOO}:${PORT_SERVICE_CONTAINER_ODOO}"
    volumes:
      - odoo-web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./enterprise:/mnt/extra-addons
      - ./integra:/mnt/integra-addons
      - ./custom:/mnt/custom-addons
    environment:
      - PYTHONUNBUFFERED=0    
    restart: always
  db:
    image: postgres:${POSTGRES_IMG_VERSION}
    container_name: ${PROJECT_NAME}_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data/pgdata
    networks:
      - network_odoo
  pgadmin:
    container_name: ${PROJECT_NAME}_pgadmin_container
    image: dpage/pgadmin4
    ports:
      - "${PG_ADMIN_HOST_PORT}:${PG_ADMIN_SERVICE_CONTAINER_PORT}"
    environment:
      PGADMIN_DEFAULT_EMAIL: binaural.ca@gmail.com
      PGADMIN_DEFAULT_PASSWORD: odoo
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - odoo-pgadmin:/root/.pgadmin
    networks:
      - network_odoo
volumes:
  odoo-web:
  odoo-db:
  odoo-pgadmin:

networks:
  network_odoo:
