from . import sale_order
from . import product_template
from . import res_config_settings
from . import res_company
from . import payment_mobile
from . import account_payment
from . import account_move_line
from . import payment_mobile_igtf
from . import website
from . import res_partner