from odoo.tests import tagged

from .common import TestDonationCommon


@tagged('l10n_ve_donation', 'stock_move', '-at_install', 'post_install')
class TestStockMove(TestDonationCommon):
    """_prepare_account_move_vals (accounting hook) for the outgoing
    donation picking -- same treatment already used by stock.scrap."""

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        # Some environments leave default_location_src_id/dest_id unset on
        # existing picking types -- force a recompute so these tests don't
        # depend on that pre-existing state.
        cls.picking_type_donation._compute_default_location_src_id()
        cls.picking_type_donation._compute_default_location_dest_id()
        cls.location_stock = cls.picking_type_donation.default_location_src_id
        cls.product_storable_donation = cls.env["product.product"].create({
            "name": "Storable Donation Move Test",
            "type": "product",
            "categ_id": cls.product_categ.id,
            "standard_price": 15.0,
        })

    def _create_delivery_move(self, donation_reason=None):
        picking = self.env["stock.picking"].create({
            "picking_type_id": self.picking_type_donation.id,
            "location_id": self.picking_type_donation.default_location_src_id.id,
            "location_dest_id": self.picking_type_donation.default_location_dest_id.id,
            "donation_reason": donation_reason,
        })
        move = self.env["stock.move"].create({
            "name": "Test Delivery Move",
            "product_id": self.product_storable_donation.id,
            "product_uom_qty": 1,
            "product_uom": self.product_storable_donation.uom_id.id,
            "location_id": self.picking_type_donation.default_location_src_id.id,
            "location_dest_id": self.picking_type_donation.default_location_dest_id.id,
            "picking_id": picking.id,
        })
        return picking, move

    def test_01_delivery_move_marks_is_donation(self):
        """The account move generated by an outgoing donation picking ends
        up is_donation=True (same accounting treatment as stock.scrap)."""
        picking, move = self._create_delivery_move(donation_reason="Medication for patient")
        vals = move._prepare_account_move_vals(
            credit_account_id=self.account_expense.id,
            debit_account_id=self.account_income.id,
            journal_id=self.journal_general.id,
            qty=1,
            description="Desc",
            svl_id=False,
            cost=10,
        )
        self.assertTrue(vals.get("is_donation"))
        self.assertEqual(vals.get("ref"), "Medication for patient")
        self.assertIn("Medication for patient", vals.get("ref"))

    def test_02_receipt_move_does_not_mark_is_donation(self):
        """The account move generated by a RECEIPT picking (shared flag set
        to True, code='incoming') does NOT end up is_donation=True -- the
        hook does not trigger for the direction it does not own."""
        receipt_picking_type = self.env["stock.picking.type"].create({
            "name": "Donation Receipt Move Test",
            "code": "incoming",
            "sequence_code": "TDONRCV3",
            "warehouse_id": self.warehouse_donation.id,
            "company_id": self.company.id,
            "is_donation_picking_type": True,
        })
        receipt_picking_type._compute_default_location_src_id()
        receipt_picking_type._compute_default_location_dest_id()
        picking = self.env["stock.picking"].create({
            "picking_type_id": receipt_picking_type.id,
            "location_id": receipt_picking_type.default_location_src_id.id,
            "location_dest_id": receipt_picking_type.default_location_dest_id.id,
        })
        move = self.env["stock.move"].create({
            "name": "Test Receipt Move",
            "product_id": self.product_storable_donation.id,
            "product_uom_qty": 1,
            "product_uom": self.product_storable_donation.uom_id.id,
            "location_id": receipt_picking_type.default_location_src_id.id,
            "location_dest_id": receipt_picking_type.default_location_dest_id.id,
            "picking_id": picking.id,
        })
        self.assertFalse(picking._is_donation_delivery())
        vals = move._prepare_account_move_vals(
            credit_account_id=self.account_expense.id,
            debit_account_id=self.account_income.id,
            journal_id=self.journal_general.id,
            qty=1,
            description="Desc",
            svl_id=False,
            cost=10,
        )
        self.assertFalse(vals.get("is_donation"))

    def test_03_delivery_move_vals_force_company_on_every_line(self):
        """Every line in vals["line_ids"] generated for a donation delivery
        must be forced to the company partner, even though the header
        (vals["partner_id"], resolved by Odoo core from the picking's
        partner_id) is left as the real beneficiary. Core's own
        `_generate_valuation_lines_data` stamps the same beneficiary on
        every line it builds; `_check_partner_donation()` (line-level
        validation, untouched) rejects any line that is not the company.

        This scenario also has a recipient set but NO `donation_reason` --
        regression test for the bug where the override unconditionally
        forced `ref` to the (here empty) `donation_reason`, discarding
        whatever `ref`/description the core `vals` already carried: `ref`
        must stay non-empty (the preserved description), not get wiped to
        `False`."""
        picking, move = self._create_delivery_move()
        picking.partner_id = self.partner
        vals = move._prepare_account_move_vals(
            credit_account_id=self.account_expense.id,
            debit_account_id=self.account_income.id,
            journal_id=self.journal_general.id,
            qty=1,
            description="Desc",
            svl_id=False,
            cost=10,
        )
        self.assertTrue(vals.get("is_donation"))
        self.assertEqual(vals.get("partner_id"), self.partner.id)
        self.assertEqual(vals.get("ref"), "Desc")
        self.assertTrue(vals.get("line_ids"))
        for command in vals["line_ids"]:
            self.assertEqual(command[2]["partner_id"], self.env.company.partner_id.id)
