from . import hikcentral_user
from . import calendar_event
from . import hikcentral_visitor_appointment
from . import res_partners
from . import action_partner
from . import hikcentral_department
from . import hikcentral_access_level
from . import membership_type_plan
from . import realtime_message_config
from . import res_company
from . import res_config_settings
from . import cadipa_access_history