{
    "name": "Binaural Retenciones",
    "summary": """
       Modulo de extensiones de pago """,
    "license": "LGPL-3",
    "author": "Binauraldev",
    "website": "https://binauraldev.com/",
    "category": "Accountant/Accountant",
    "version": "16.0.19.1.7",
    # any module necessary for this one to work correctly
    "depends": [
        "base",
        "account",
        "binaural_rate",
        "binaural_accountant",
        "binaural_invoice",
        "binaural_location",
        "binaural_fiscal",
        "binaural_contact",
        "binaural_tax_payer",
        "product",
    ],
    # always loaded
    "data": [
        "security/ir.model.access.csv",
        "security/ir_rule.xml",
        "data/sequence_data.xml",
        "data/type_person_data.xml",
        "data/account_withholding_type_data.xml",
        "data/report_paperformat_data.xml",
        "data/tax_unit_data.xml",
        "data/fees_retention_data.xml",
        "data/payment_concept_data.xml",
        "report/retention_line_report_views.xml",
        "report/retention_voucher_templates.xml",
        "report/retention_voucher_reports.xml",
        "report/arcv_report.xml",
        "views/ir_sequence.xml",
        "views/res_config_settings.xml",
        "views/tax_unit.xml",
        "views/fees_retention.xml",
        "views/economic_activity.xml",
        "views/economic_branch.xml",
        "views/payment_concept.xml",
        "views/product.xml",
        "views/product_category.xml",
        "views/res_company.xml",
        "views/signature_config.xml",
        "views/type_withholding.xml",
        "views/account_retention_line.xml",
        "views/account_retention_iva.xml",
        "views/account_retention_islr.xml",
        "views/account_retention_municipal.xml",
        "views/account_payment.xml",
        "views/res_partner.xml",
        "views/account_move.xml",
        "wizard/account_payment_register.xml",
        "wizard/arcv_report.xml",
        "wizard/municipal_retention_xlsx_report.xml",
        "wizard/municipal_retention_patent_report.xml",
        "wizard/wizard_retention_islr.xml",
        "wizard/wizard_retention_iva.xml",
        "views/menu.xml",
    ],
    "images": ["static/description/icon.png"],
    "application": True,
    "binaural": True,
}
