{
    "name": "Binaural Sucursales",
    "summary": """Integración de cuentas analíticas como sucursales""",
    "license": "LGPL-3",
    "author": "Binauraldev",
    "website": "https://binauraldev.com/",
    "version": "16.0.4.0.0",
    "category": "Accountant",
    "depends": [
        "analytic",
        "purchase",
        "binaural_accountant",
        "binaural_invoice",
        "binaural_purchase",
        "binaural_sale",
    ],
    "data": [
        "data/account_analytic_account.xml",
        "report/sale_report.xml",
        "report/purchase_report.xml",
        "report/account_invoice_report.xml",
        "views/account_move.xml",
        "views/account_payment.xml",
        "views/analytic_account.xml",
        "views/purchase_order.xml",
        "views/res_users.xml",
        "views/sale_order.xml",
        "views/menuitems.xml",
        "wizard/account_payment_register.xml",
        "wizard/accounting_report_views.xml",
    ],
    "images": ["static/description/icon.png"],
    "application": True,
    "post_init_hook": "activate_series_invoicing",
}
