{
    "name": "Binaural Sucursales",
    "summary": """Integración de cuentas analíticas como sucursales""",
    "license": "LGPL-3",
    "author": "Binauraldev",
    "website": "https://binauraldev.com/",
    "version": "16.0",
    "category": "Accountant",
    "depends": [
        "purchase",
        "binaural_accountant",
        "binaural_sale",
        "binaural_purchase",
    ],
    "data": [
        "views/account_payment.xml",
        "views/res_config_settings.xml",
        "views/account_move.xml",
        "views/purchase_order.xml",
        "views/analytic_account.xml",
        "wizard/account_payment_register.xml",
    ],
    "images": ["static/description/icon.png"],
    "application": True,
}
