{
    "name": "Binaural Movil",
    "summary": """
        Integración para app de vendedores..
    """,
    "description": """
       Modulo para servir de integración con app de vendedores. 
    """,
    "license": "LGPL-3",
    "author": "Binauraldev",
    "website": "https://binauraldev.com/",
    "version": "16.0.2.3.16",
    "category": "Human Resources/Stock/Sales/Invoicing",
    "depends": [
        "web",
        "website",
        "portal",
        "website_sale",
        "binaural_brand",
        "binaural_seller",
        "binaural_sale",
        "binaural_stock",
        "binaural_payment_extension",
        "theme_prime",
        "product",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_rule.xml",
        "data/res_groups.xml",
        "views/portal_budget.xml",
        "views/website_templates.xml",
        "views/portal_templates.xml",
        "views/portal_invoice_seller.xml",
        "views/portal_payment.xml",
        "views/res_config_settings.xml",
        "views/sale_order_views.xml",
        "views/sale_portal_templates.xml",
        "views/account_portal_template.xml",
        # "views/shop_layout.xml",
        "views/templates.xml",
        "views/payment_mobile_view.xml",
        "views/payment_mobile_igtf_view.xml",
        "views/payment_mobile_menu.xml",
        "views/pwa.xml",
        "views/website_sale_wishlist_template.xml",
        "views/account_payment.xml",
        "views/product_template.xml",
        "views/res_partner.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "binaural_mobile/static/src/js/portal_budget.js",
            "binaural_mobile/static/src/js/portal_invoice.js",
            "binaural_mobile/static/src/js/portal_payment.js",
            "binaural_mobile/static/src/js/portal_payment_info.js",
        ]
    },
    "images": ["static/description/icon.png"],
    "application": True,
    "binaural": True,
}
