{
    "name": "Binaural Nómina",
    "summary": """Personalizaciones de nómina para Venezuela""",
    "author": "Binauraldev",
    "license": "LGPL-3",
    "website": "https://www.binauraldev.com",
    "category": "Payroll Localization",
    "version": "17.0.1.0.0",
    # any module necessary for this one to work correctly
    "depends": ["hr", "hr_payroll", "hr_work_entry_contract_enterprise", "binaural_rate"],
    # always loaded
    "data": [
        "data/hr_work_entry_type.xml",
        "data/resource_calendar.xml",
        "data/hr_payroll_structure_type.xml",
        "security/ir.model.access.csv",
        "views/hr_allowance.xml",
        "views/hr_allowance_line.xml",
        "views/hr_contract.xml",
        "views/hr_employee.xml",
        "views/hr_payroll_move.xml",
        "views/hr_payroll_structure.xml",
        "views/hr_payroll_structure_type.xml",
        "views/hr_payslip.xml",
        "views/hr_payslip_payment_method.xml",
        "views/hr_payslip_run.xml",
        "views/hr_payslip_run_report_templates.xml",
        "views/hr_payslip_run_report_views.xml",
        "views/hr_payslip_input_type.xml",
        "views/hr_salary_rule_category.xml",
        "views/hr_salary_rule.xml",
        "views/report_payslip_templates.xml",
        "views/res_config_settings.xml",
        "views/menuitems.xml",
    ],
    "binaural": True,
}
