from . import browsable_object
from . import hr_allowance
from . import hr_contract
from . import hr_employee
from . import hr_payroll_move
from . import hr_payroll_structure
from . import hr_payslip_run
from . import hr_payslip
from . import hr_payslip_line
from . import hr_payslip_worked_days
from . import hr_salary_rule
from . import resource_calendar_attendance
from . import res_company
from . import res_config_settings
