name: Auto-delete abandoned branches every morning.

on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  contents: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: game8inc/cull@v1
      with:
        repo-token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        dry-run: 'true'
        older-than: '10'
        max-deletion-per-day: '5'