name: Auto-delete abandoned branches every morning.

on:
  schedule:
    - cron: "0 15 * * *"

permissions:
  contents: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: game8inc/cull@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: 'true'
        older-than: '10'
        max-deletion-per-day: '5'
