name: tag
on:
  workflow_dispatch:
jobs:

  create_pull_request:    
    runs-on: ubuntu-latest
    permissions: read-all      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: List forked repositories
      id: list_forks      
      run: |
        # Obtiene la lista de proyectos destino (forks de integra) usando la API de GitHub        
        curl -s -H "Authorization: token ${{ secrets.KEY_DEPLOY }}" -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/binaural-dev/integra/forks \
          | jq -r '.[] | .full_name' \
          | tee forks.txt      

    - name: Create PRs to Projects      
      run: |
        # Itera sobre la lista de proyectos destino        
        while IFS= read -r project; do
          echo "Creating PR to $project"
          sleep 3
          # Crea un pull request desde release-16 en binaural-dev/integra hacia staging en el proyecto destino
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.KEY_DEPLOY }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"title": "Merge release-16 into staging", "body": "Cambios de integra al proyecto", "head": "release-16", "head_repo": "binaural-dev/integra" , "base": "staging"}' \
            "https://api.github.com/repos/$project/pulls"
          echo "Creado PR a $project"
        done < forks.txt
        echo "Done"

