name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - release-16
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
        if: ${{ steps.tag_version.outputs.new_tag }}

  create_pull_request:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: List forked repositories
      id: list_forks
      run: |
        # Obtiene la lista de proyectos destino (forks de integra) usando la API de GitHub
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/binaural-dev/integra/forks" \
          | jq -r '.[] | .full_name' \
          | tee $GITHUB_WORKSPACE/forks.txt

    - name: Create PRs to Projects
      run: |
        # Itera sobre la lista de proyectos destino
        while IFS= read -r project; do
          echo "Creating PR to $project"
          # Crea un pull request desde release-16 en binaural-dev/integra hacia staging en el proyecto destino
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title": "Merge release-16 into staging", "head": "binaural-dev:integra/release-16", "base": "staging"}' \
            "https://api.github.com/repos/$project/pulls"
        done < $GITHUB_WORKSPACE/forks.txt
        echo "Done"

